### PR TITLE
Divided according to difficulty level

### PR DESCRIPTION
**Pull request by Sandeep-source**
Hey @31Sanskrati ,

Can you review this PR ?

### CODE REVIEW

**Comment by Sandeep-source** [comment]
Hey @31Sanskrati,
Can you review this one, Maybe you missed it.
Is there any modification needed ?

#26

**Review by 31Sanskrati — CHANGES_REQUESTED** [review]
Please remove the topic column from the table. That would help in maintaining the new format of the table

**Review by 31Sanskrati — APPROVED** [review]
The code is perfectly fine. But please make the necessary changes.

Again thank you for the PR

**Comment by Sandeep-source** [comment]
@31Sanskrati 

That's my bad.

Thanks for the review, Now it looks good to go.

**Review by 31Sanskrati — APPROVED** [review]

**Review by 31Sanskrati — APPROVED** [review]
I will merge the PR now

**Comment by Sandeep-source** [comment]
Glad that PR got merged 🎉.

**Pull request merged**
